### ISSUE TITLE
why not use RxTextView to replace it?

### ISSUE THREAD

**Issue by nickming** [SmartDengg/sug-debounce#1]

**Comment by SmartDengg** [comment]
Because `RxTextView` can not solve the debounce problem, it's just rxjava's wrapper for `TextView`.

**Comment by nickming** [comment]
```
        RxTextView.textChanges(edittext)
                .skipInitialValue()
                .debounce(500, TimeUnit.MILLISECONDS)
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe({
                    textview.text = text.toString()
                }, {
                    Log.w("test", it.localizedMessage)
                })
```
I think RxTextView is also a Observable,may should use debeunce function

**Comment by SmartDengg** [comment]
Obviously, if you use `RxTextView`, it means you should dependence the rxjava library, I don't want to introduce the whole rxjava library just to use the `debounce` operator, which is a waste!!!
So, I use some judgment logic internally. If rxjava in the classpath, use the operator such as`debounce`. Otherwise, use the standard Android local API instead. 
I will not introduce dependencies, i just wrapper it.

**Comment by nickming** [comment]
ok,thanks
